"Type: Engine":
- changed-files:
  - any-glob-to-any-file: '**/Engine.*'

"Type: SDK":
- changed-files:
  - any-glob-to-any-file: '**/SDK.*'

"Type: Anti-Cheat":
- changed-files:
  - any-glob-to-any-file: '**/AntiCheat.*'

"Type: Launcher":
- changed-files:
  - any-glob-to-any-file: '**/Launcher.*'

"Type: Programming-Language":
  - '**/Programming-Language.*'

"Type: Container":
- changed-files:
  - any-glob-to-any-file: '**/Container.*'
